# Server configurations
server:
  host: "localhost"
  port: 8000

# Database credentials
database:
  user: ""
  pass: ""
  host: "127.0.0.1"
  port: "27017"
  dbname: "sweepdb"

#Custodian configurations
custodian:
  c7nawsinstall: "/home/vboxuser/custodian/bin/activate"