# Server configurations
server:
  host: "localhost"
  port: 8000

# Database credentials
database:
  user: ""
  pass: ""
  host: "127.0.0.1"
  port: "27017"
  dbname: "sweepdb"

#Custodian configurations
custodian:
  c7nawsinstall: "/home/vboxuser/custodian/bin/activate"

# Admin AWS Creds
aws:
  creds:
    aws_access_key_id: ""
    aws_default_region: ""
    aws_secret_access_key: ""

# Logging details, max_size in MB, max_age in Days
logging:
  default_log_file: "./cs_runner.log"
  max_size: 1
  max_backups: 5
  max_age: 28
