# Server configurations
server:
  host: "localhost"
  port: 8000

# Database credentials
database:
  user: ""
  pass: ""
  host: "127.0.0.1"
  port: "27017"
  dbname: "sweepdb"

#Custodian configurations
custodian:
  c7nawsinstall: "/home/vboxuser/custodian/bin/activate"

# Admin AWS Creds
aws:
  creds:
    aws_access_key_id: "AKIA4T2VWH7A6GQYCS7Z"
    aws_default_region: "us-east-1"
    aws_secret_access_key: "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"

# Logging details, max_size in MB, max_age in Days
logging:
  default_log_file: "./cs_runner.log"
  max_size: 1
  max_backups: 5
  max_age: 28

openai:
  openai_url: "https://api.openai.com/v1/chat/completions"
  openai_apikey: ""

makersuite:
  palm_url: ""
  palm_key: ""

notifications:
  email:
    host: "smtpout.secureserver.net"
    port: 25
    username: "no-reply@cloudsweeper.in"
    password: "CloudSw33p3r@1"
    from_address: "no-reply@cloudsweeper.in"

cloudsweeper:
  logo: "/home/pavan/Documents/cs.jpg"
  url: "https://cloudsweeper.in/"